### ISSUE TITLE
Expose Observables

### ISSUE THREAD

**Issue by opsb** [orbitjs/ember-orbit#114]
From gitter

> opsb> One question @cowboyd, the Observables emit the orbit operations, is that would you would expect or would you expect the updated data structures? i.e. would you expect the complete array of results to be emitted on each change or the orbit operation containing the change?
> (currently ember-orbit takes care of converting the orbit operations into the final data structures)
> 
> cowbodyd> @opsb I’d expect that a query would return a cursor to some point in the datastructure
> and that iterating on that cursor would yield versions of the object it pointed to.

Currently `store.liveQuery()` returns an ArrayProxy which contains the results so the Observable isn't actually exposed. This issue is to discuss the best way to expose the underlying Observable.

1) option to `liveQuery()`

```
store.liveQuery(oql, { esObservable: true }) => Observable
store.liveQuery() => ArrayProxy
```

2) two stage

```
store.liveQuery() => Observable
store.liveQuery().asArrayProxy() => ArrayProxy
```

allowing e.g.

```
store.liveQuery().map(sortByName).asArray()
```

3) separate store methods

```
store.observableQuery() => Observable
store.liveQuery() => ArrayProxy
```

(naming needs more thought)

My preferred option would probably be (2), it feels the most natural and it allows for adding shortcuts like (1) and (3) later if desired.

**Comment by dgeb** [comment]
Orbit is no longer directly using Observables, although an rxjs-orbit wrapper lib should be considered. Even so, it's unlikely that ember-orbit will depend on such a wrapper.
