### ISSUE TITLE
Using hyphenated type for Store.find throws error

### ISSUE THREAD

**Issue by mitchlloyd** [orbitjs/ember-orbit#116]
Using a hyphenated type for `store.findRecord` throws an error:

```
OC.RecordNotFoundException: Record not found evidence-request:1/undefined
```

Example usage: 

```js
this.store.findRecord('evidence-request', 1);
```

This code will:
1. fetch the record over the network
2. add it to the cache's `_doc` under 'evidenceRequests'
3. attempt to `query` the cache with `evidence-request` type.
4. Throw the exception

Using a camelCased type works:

```js
this.store.findRecord('evidenceRequest', 1);
```

**Comment by dgeb** [comment]
Types are by default assumed to be singular and camel-cased (e.g. `evidenceRequest`) within ember-orbit (and orbit-common), and then are translated to a pluralized, dasherized form in the JSONAPISerializer. This translation explains why the request was processed, but then the error was thrown when the record was looked up by type.

I'm sure that this will be confusing to some, and maybe we should concede to ember-data's conventions to minimize heartburn. Or we could be forgiving and camelize any types passed in as public arguments.

**Comment by mitchlloyd** [comment]
Seems fine to depart from the Ember Data convention, but it would be nice to get a better error sooner, ideally before making a network request. I'll take a look at this.

**Comment by dgeb** [comment]
@mitchlloyd do you think we can close this now that https://github.com/orbitjs/orbit.js/issues/331 has been merged?

**Comment by mitchlloyd** [comment]
Yep! I think forthcoming documentation and a better error message here resolve this issue.
