### ISSUE TITLE
Store needs to support `relatedRecords` query

### ISSUE THREAD

**Issue by mitchlloyd** [orbitjs/ember-orbit#127]
When doing a `relatedRecords` query, I'm not getting records back. The issue appears to be in [this switch statement](https://github.com/orbitjs/ember-orbit/blob/master/addon/store.js#L87-L91).

Adding this line fixes it:

```js
switch(query.expression.op) {
  case 'record':  return this._identityMap.lookup(result);
  case 'relatedRecords': return this._identityMap.lookupMany(objectValues(result)) // <- Added
  case 'records': return this._identityMap.lookupMany(objectValues(result));
  case 'filter':  return this._identityMap.lookupMany(objectValues(result));
  default:        return result;
}
```

Looking at [the list of methods in the query builder](https://github.com/orbitjs/orbit-core/blob/e46058f360ce79909c0a79acc66dd41798daba7d/src/query/builder.js), it seems that `relatedRecord` is missing to.

It would be nice if there were some way to loosen up this coupling between these 2 different repos. Maybe methods like `query.isForMany`, `query.isForOne` or some meta data on the results.

**Comment by dgeb** [comment]
> It would be nice if there were some way to loosen up this coupling between these 2 different repos. Maybe methods like query.isForMany, query.isForOne or some meta data on the results.

@mitchlloyd I tend to agree about the coupling problem. Let's think on the best way to approach this. For now, I'll fix `relatedRecord` and `relatedRecords`.
