### ISSUE TITLE
ember-data on some models.

### ISSUE THREAD

**Issue by johnunclesam** [orbitjs/ember-orbit#150]
To all of you I ask to excuse my ignorance.

With `ember-orbit` can I still use `ember-data` on some models?

**Comment by dgeb** [comment]
@johnunclesam Sorry for the delay in responding. 

I have not yet used `ember-orbit` and `ember-data` together in the same project. I think that currently there are some conflicts, such as both registering a `store` service and potential conflicts re: model registrations. It seems possible to work around these conflicts by customizing the initializers and allowing either `ember-orbit` or `ember-data` to be the default.

The ideal path for using Orbit together with ember-data will probably be through the [Model Data](https://github.com/emberjs/rfcs/pull/293) interface (see the RFC for a discussion of Orbit + ember-data). More on this soon!
