### ISSUE TITLE
Error when trying to query the store

### ISSUE THREAD

**Issue by piotrpalek** [orbitjs/ember-orbit#156]
Hey, I've installed ember-orbit, made one model:

```
import {
  Model,
  attr
} from 'ember-orbit';

export default Model.extend({
  name: attr('string'),
  phoneNumber: attr('string')
});
```
in `app/models/thread.js` and tried to query the store which resulted in this error:
`Uncaught (in promise) Error: Unable to find operator: undefined Error: Unable to find operator: undefined`. Am I doing something wrong here?

![image](https://user-images.githubusercontent.com/1474323/39359608-f4ab1e2a-4a1a-11e8-9874-56fbcdabc2bb.png)

**Comment by dgeb** [comment]
`store.query` requires a query expression or a query builder as an argument.

For instance: `store.query(q => q.findRecords('contact'));`

See http://orbitjs.com/v0.15/guide/querying-data.html#Standard-queries for more options.

**Comment by dgeb** [comment]
>  Maybe I'm missing something?

No, I didn't review carefully. Sorry for the premature closure.

**Comment by piotrpalek** [comment]
No worries, I should've made the issue clearer by including the main error in it (as text) :)

**Comment by maksimsemenov** [comment]
Are there any updates on that? I'm having the same issue.

I'm trying to query an in-memory store:
```
store.query(q => q.findRecords('patient'))
```

And getting the same error:
```
Uncaught (in promise) Error: Unable to find operator: undefined
```

**Comment by maksimsemenov** [comment]
I figure out what was causing an issue in my case. When I add a bucket (IndexedDBBucket) to the sources (Store, JSONAPI), then weird queries get dispatched on that sources:
```
{
   expression: {
      expression: undefined,
      id: "dab22f7f-4d9b-4d01-907e-6457d485faba",
      options: undefined
   },
   id: "7f902646-389d-4de7-96c1-2fd87542568b",
   options: undefined
}
```
Sources do not know how to deal with this type of queries.

Not sure if that is intentional behavior and if I'm missing something, but hope it might be helpful.

**Comment by dgeb** [comment]
I believe this should be resolved now that we've introduced an explicit source activation / deactivation process.
