### ISSUE TITLE
remoteId is undefined

### ISSUE THREAD

**Issue by simonihmig** [orbitjs/ember-orbit#174]
Following up on the discussion on [Gitter](https://gitter.im/orbitjs/orbit.js?at=5c66b50a5095f6660cfb1f0b), after long back and forth trying to replicate the case where newly created records show up with a `remoteId` of `undefined`, I was finally able to replicate this in a minimal way, and isolate the conditions that cause that error.

Here's the repo: https://github.com/simonihmig/test-ember-orbit

AFAICT this seems to be a race condition to me, around when `remoteId` is first accessed. It is defined as a CP, without any dependent keys. Which in general is fine I guess, since the remote ID is not expected to change. But the case here was that it was first read from when the `remoteId` has not yet been applied to the underlying orbit record, so the CP returns `undefined`, and that will stay so forever then, even when the `remoteId` is set on the record later.

One critical piece that was missing from the original reproduction repo was setting the bucket for the source [here](https://github.com/simonihmig/test-ember-orbit/blob/master/app/initializers/orbit.js#L2). Finding that out was only possible after hours-long trial and error... 🙄. I don't believe using the bucket is the root issue, but just a condition that influences the race condition in a negative way, as it seems to delay the processing of transformations.

Given [this logging call](https://github.com/simonihmig/test-ember-orbit/blob/master/app/templates/application.hbs#L3) in the template, we can see when the new record is rendered and what the `remoteId` is.

With the bucket activated, the console after adding a record looks like this:

![image](https://user-images.githubusercontent.com/1325249/52898698-41a13f80-31e1-11e9-9a45-827ddfd2726e.png)

There are two transforms being processed, one `addRecord` and one `replaceKey` (remoteId). The template is already rerendered after the first transform, but because of the missing `replaceKey` operation `remoteId` is `undefined`.

When I comment out the bucket injection, the log looks like this:

![image](https://user-images.githubusercontent.com/1325249/52898810-e5d7b600-31e2-11e9-991a-788f6d3f9562.png)

Note the final log entry of `3`. Obviously the rendering happens later, when the `remoteId` is already available, and things work fine.

In my particular case, I would be able to workaround this by override the `key` CP with one that is volatile (though that's being deprecated), as I am programmatically accessing the `remoteId` in an action. But that wouldn't fix the case in the reproduction repo, where it is rendered in a template, as the volatile CP won't update automatically.

Without having a deep understanding of all that's happening under the hood, I wonder if it would be possible to aggregate those two separate transforms (each has one operation) into a single one (with two operations, `addRecord` and `replaceKey`), effectively making this an atomic operation AFAIK?

**Comment by dgeb** [comment]
@simonihmig thanks for this reproduction! I've identified the source of the problem and will issue a patch ASAP.

**Comment by dgeb** [comment]
@simonihmig This should be fixed in v0.15.11 - please let me know if you have further issues.
