### ISSUE TITLE
How can I generate UUIDs client side?

### ISSUE THREAD

**Issue by tute** [orbitjs/ember-orbit#18]
I have the following code in my orbit initializer:

``` js
var Schema = EO.Schema.extend({
  idField: 'id',
  remoteIdField: 'id',

  generateId: function() {
    var s4 = function () {
      return Math.floor((1 + Math.random()) * 0x10000)
                 .toString(16)
                 .substring(1);
    };
    return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
           s4() + '-' + s4() + s4() + s4();
  }
});
// ...
application.register('schema:main', Schema);
```

The goal is to generate UUIDs client side, and let the server know so. I can see how `ifField` is now preset from the first `memoryStore` I have defined, but orbit doesn't seem to see my own `generateId` UUID generator function. What is the proper way to extend the `Schema` to add such behavior?

Thank you!

**Comment by Cryrivers** [comment]
Could I know how to override `generateId` in latest `ember-orbit`? Thanks!
