### ISSUE TITLE
Remote id in routes

### ISSUE THREAD

**Issue by nayrban** [orbitjs/ember-orbit#212]
Hey guys, I have a doubt,  I am running some test cases with selenium for our backend (integration tests) anyway, the situation is when I open the browser, in this case, chrome, I am sending the remote-id because of I don't have the orbit-js generated id for that record. So my question is, there is an option to do http://url:port#/model/remote-id and should be translated to  http://url:port#/model/local-id

**Comment by dgeb** [comment]
You can call [`store.findRecordByKey()`](https://github.com/orbitjs/ember-orbit/blob/master/addon/-private/store.ts#L174-L185) or [`store.cache.peekRecordByKey()`](https://github.com/orbitjs/ember-orbit/blob/master/addon/-private/cache.ts#L106-L112) and those methods will create a local id for the record that's associated with the `remoteId` in the `KeyMap` (if no mapping already exists). And the remote id should always be used in requests if the serializer's `resourceKey` method returns `remoteId`.

**Comment by nayrban** [comment]
Thanks @dgeb for your answer, I appreciate your time on this,  It helps us a lot

**Comment by nayrban** [comment]
just let you know, I will first check if the id its a remote id and based on that I will decide if perform the query or just use the provided local id
