### ISSUE TITLE
[Ember.js 3.11.1] "TypeError: Cannot read property 'identity' of undefined" when adding a record

### ISSUE THREAD

**Issue by YoranBrondsema** [orbitjs/ember-orbit#213]
I get the following error when adding a record in the Memory source. The error happens only in the `production` environment (not in development), for Ember.js 3.11.1, and it's triggered by line https://github.com/orbitjs/ember-orbit/blob/v0.16.0/addon/-private/model.ts#L30.

```
TypeError: Cannot read property 'identity' of undefined
```

I noticed the error while introducing Orbit.js to my app. It's the first time that I use Orbit.js so I'm not familiar with the code base. Hence the limited use of this bug report.

**Comment by dgeb** [comment]
@YoranBrondsema this should be resolved by #215. Thanks for reporting!

**Comment by YoranBrondsema** [comment]
Awesome, thanks!
