### ISSUE TITLE
Offline mode strategy

### ISSUE THREAD

**Issue by nayrban** [orbitjs/ember-orbit#217]
Hi guys, 
I have a question-doubt about some strategies that I am defining for a offline mode.

So a brief context, we are developing an application that has the capability to work in offline/online mode. So basically we have a listener that updates the strategies for each mode depending on the browser navigator.onLine property. So, thinking in offline mode we define a strategy as follow:

`create() {

    return new RequestStrategy({
      name: 'store-remote-update-offline',
      source: 'store',
      on: 'beforeUpdate',

      target: 'remote',
      action(transform) {
        const coordinator = this.coordinator;
        const remote = coordinator.getSource('remote');
        const store = coordinator.getSource('store');

        return   remote.push(transform);
      },

      blocking: false
    });

   },
`

Our idea with this was to enqueue each record created when offline to then push then to the server when available, as obviously, this is going to fail with a Network Error we define another strategy with an on:pushFail that has a retry to the server in a specific interval time.

` create() {

    return new RequestStrategy({
      name: 'remote-push-fail',

      source: 'remote',
      on: 'pushFail',

      action(transform, e) {
        const coordinator = this.coordinator;
        const remote = coordinator.getSource('remote');
        const store = coordinator.getSource('store');

        if (e instanceof NetworkError) {
          setTimeout(() => {
            remote.requestQueue.retry();
          }, 5000);

        } else {

          // Roll back store to position before transform
          if (store.transformLog.contains(transform.id)) {
            store.rollback(transform.id, -1);
          }
          return remote.requestQueue.skip();
        }
      },

      blocking: false
    });`

So, from here all is so far so good, it works, but for some reason not all the time. I was debugging the code and I was noticed        ` return   remote.push(transform);` that this promise is not always resolved/rejected, but the push is well enqueued, so its something really weird, at least to me :D. 
I have defined and added all the sources, remote, backup and store.

I  defined both strategies as  ` blocking: false ` 

A point that I want to mention is, that this app is working as PWA with a service worker. But also removing all the local storage and the services worker  (using the Chrome development tools) I get the same behavior some times.

Most of our work here is based on the demo app.
We are using `ember-orbit:"^0.15.11"`

Thank you so much guys.

**Comment by dgeb** [comment]
@nayrban Sorry to take a bit to respond. Your general approach looks good at first glance, but it's tricky to debug without an example app or failing test.

I've just released a new example app that illustrates a number of different connection strategies and documents different approaches to error handling in the README: https://github.com/orbitjs/todomvc-ember-orbit

Note that the optimistic error handling section is very similar to what you've described here.

This example uses v0.16.2 of ember-orbit, which I would highly recommend you upgrade to if possible. If you review the changelogs and release notes for both the orbit and ember-orbit repos, you'll see quite a few fixes made between v0.15 and v0.16, and not that many breaking changes. The [What's new](https://orbitjs.com/v0.16/guide/whats-new.html) section in the guides is probably the easiest way to digest these changes and (hopefully) convince you to upgrade.

With that said, I'm willing to make some quick fixes to v0.15 if you can provide a failing test on the `release-0-15` branch, but I'd much prefer to focus on v0.16 and beyond.

**Comment by nayrban** [comment]
Hi @dgeb I did the upgrade to 0.16.x and now it works
`action(transform, e) {`


but I found that `action` is not sending the `exception` anymore and I guess It was my error in the past versi

**Comment by dgeb** [comment]
@nayrban Hmmm ... make sure that you're using v0.16.2 of `@orbit/coordinator` which fixed a related bug. If that still doesn't fix it, and you want me to check it out, you could try to recreate the problem in a fork of the todomvc-ember-orbit demo using the error handling strategy described in scenario 4.

**Comment by nayrban** [comment]
sure, thanks I will try to see if it work in the correct way and I will let you know, thanks again

**Comment by nayrban** [comment]
@dgeb I haven't had much time these days to test it, but I will let you know when I get some chance

**Comment by dgeb** [comment]
@nayrban can this be closed?

**Comment by nayrban** [comment]
yes @dgeb , I am going to close it

**Comment by nayrban** [comment]
I just did the update to use the action method and its working as expected thanks @dgeb
