### ISSUE TITLE
Querying from cache

### ISSUE THREAD

**Issue by nayrban** [orbitjs/ember-orbit#228]
Hey guys,
I have a question about how the `cache` query works 

My scenario, I want to query the remote server only if there are no records on cache (and probably after a time strategy, that maybe anyone can help on how to handle that, but I can describe that later).

I have the following data-strategy
`
import { RequestStrategy } from '@orbit/coordinator';

export default {
  create() {
    return new RequestStrategy({
      name: 'store-remote-query',

      source: 'store',
      on: 'beforeQuery',

      target: 'remote',
      action: 'pull',

      blocking: true,

      // Only fetch from server, if we don't have local data in cache
      //TODO the only thing I have so far in mind is how to handle the update interval for sync
      filter(query) {
        const coordinator = this.coordinator;
        const store = coordinator.getSource('store');

        let dataInCache = store.cache.query(query, query.options);
        return dataInCache.length <= 0;
      },

      catch(e) {
        this.source.requestQueue.skip();
        this.target.requestQueue.skip();

        throw e;
      }
    });
  },
};
`
so the idea with that is, as I described, request the server only if necessary

`
return this.store.liveQuery(q => q.findRelatedRecords({type: 'teacher', id: model.get('id')}, 'observations'), {
      label: "Find all observations",
      sources: {
        remote: {
          include: ['sessions', 'sessions.activities']
        }
      }
    });
`
My concerns are related to this query that requires a deep level of relationships, because `store.cache.query` only use the query.expression not matter what options you have. 

So I guess I am using the wrong method or approach 

@dgeb

**Comment by dgeb** [comment]
The strategy and `filter` that you've provided should only perform a remote query (or `pull`) if records don't exist in the cache. Is that working as you expect?

A `liveQuery` will only issue an initial `query` once and then will continue to observe changes to its associated cache. But this is passive, so if you want to force periodic `remote` checks, you'll want to reissue that same query periodically against your remote source and allow the results to sync with your cache.

**Comment by nayrban** [comment]
> The strategy and filter that you've provided should only perform a remote query (or pull) if records don't exist in the cache. Is that working as you expect?

Yes it is how the strategy works and if not in cache is working fine, but the issue that I have is:
teachers are in cache, observations are in cache and also sessions, but activities are not in cache. Thats why I add `{ include: ['sessions', 'sessions.activities'] }`, but this option is not included in the cache query

**Comment by dgeb** [comment]
@nayrban the query options you're sending ( `sources: { remote: { include: ['sessions', 'sessions.activities'] } }` ) are specific to the `remote` source. The cache itself will ignore them, and only the `remote` source will even be aware of them.

If the remote source is properly applying the `include` parameter in the query string sent to your server, then the query is working as expected.

The live query you've created should be updated whenever the cache receives an update to this particular teacher's "observations". Furthermore, as sessions and activities are updated in the cache, any model instances should be updated to reflect those updates.

Your question seems to be how to periodically update this whole graph of data from the server. You could either push changes from a web socket, or periodically poll for updates by re-issuing the query against your server.

If I'm misunderstanding, please restate what you're trying to accomplish.

**Comment by nayrban** [comment]
thanks @dgeb , so that means, leaving the cache aside, because I now get it how it works, that if I include remote ( `sources: { remote: { include: ['sessions', 'sessions.activities'] } }` ) this will always make the query to the server?

**Comment by dgeb** [comment]
@nayrban as long as the `filter` in your strategy is satisfied, issuing that query on the store will reach the remote source, which will query the server. And then your sync strategy should populate the store, and the live query will stay updated.

You won't need to issue a _live_ query every time you want new data. If you're able to hold onto a reference to the live query result set, it will stay updated as results that match flow into the cache. However, you'll need to do something, like re-querying the remote source (either directly or via the store) to refresh this data.
