### ISSUE TITLE
serializer and adapter for ember-orbit

### ISSUE THREAD

**Issue by sarangsbabu367** [orbitjs/ember-orbit#233]

**Comment by tchak** [comment]
Orbit source is the equivalent of an adapter. Orbit serializer is a thing. Do you mean you wish it would be easier to plug a custom serializer through injection system?

**Comment by sarangsbabu367** [comment]
No, it is not necessary i wasnt digging to the source code. When i tried to
understand the source then i found that extending the jsoapi source classes
will do the serializer and adapter. But for beginners, it will be
difficult, but it is simple if we understand the concept. You can provide
some docs about extending the classes like "urlbuilder class" etc.

**Comment by dgeb** [comment]
I agree we need to improve the docs especially for `@orbit/jsonapi`. These are coming with v0.17.
