### ISSUE TITLE
Unknown Injection: `data-bucket:main`

### ISSUE THREAD

**Issue by aalasolutions** [orbitjs/ember-orbit#238]
I am following tutorial, and I am stuck on this step.

Here is my Ember Info

Library | Version
-- | --
Ember Inspector | 3.13.1
Ember | 3.15.0
jQuery | 3.4.1
Ember Bootstrap | 2.8.1
Ember Simple Auth | 1.9.2
FrontEnd | 0.0.0+246b100f

```
index.js:172 Uncaught Error: Assertion Failed: Attempting to inject an unknown injection: 'data-bucket:main'
    at assert (index.js:172)
    at Registry.proto.validateInjections (index.js:1148)
    at processInjections (index.js:382)
    at buildInjections (index.js:419)
    at injectionsFor (index.js:434)
    at FactoryManager.create (index.js:499)
    at instantiateFactory (index.js:362)
    at lookup (index.js:290)
    at processInjections (index.js:403)
    at buildInjections (index.js:423)
```

**Comment by dgeb** [comment]
@aalasolutions Sorry to hear you ran into a problem. Which tutorial are you following specifically? Are you walking through the ember-orbit readme, the Orbit v0.16 guides, or perhaps https://github.com/orbitjs/todomvc-ember-orbit ?

**Comment by aalasolutions** [comment]
Hi @dgeb thanks for your feedback, i had forgotten about it. Any how, i rolled back everything and started again from scratch and this time it worked. I have a saying that "It might have stuck in a wire" hehehe

Things are working. I am now looking at pagination. I have my app working with RESTAPI and converted the backend to (Laravel) to JSONAPI, i am getting meta information back but in my JS function it says meta is undefined. May be promise is not yet resolved. 

Any how, closing this issue.

Thanks again
