### ISSUE TITLE
addToRelatedRecords not invoking the serialiser

### ISSUE THREAD

**Issue by TheLooseCannon** [orbitjs/ember-orbit#260]
```js
response = await this.store.update((t) =>
	t.addToRelatedRecords(
		{ type: 'planet', id: this.planet_id },
		'members',
		{type: 'moon', id: this.moon_id)
	)
);
```
i have a custom serialiser configured for remote source
but the serializer is not being called when sending this request.
why is it happening? 

and also i'm not getting any response.

**Comment by TheLooseCannon** [comment]
```js
async addToRelatedRecords(
    requestProcessor: JSONAPIRequestProcessor,
    request: AddToRelatedRecordsRequest
  ): Promise<RequestProcessorResponse> {
    const { relationship, record } = request;
    const options = request.options || {};
    const { type, id } = record;
    const json = {
      data: request.relatedRecords.map((r) =>
        requestProcessor.serializer.resourceIdentity(r)
      )
    };
    const settings = requestProcessor.buildFetchSettings(options, {
      method: 'POST',
      json
    });
    const url =
      options.url ||
      requestProcessor.urlBuilder.resourceRelationshipURL(
        type,
        id,
        relationship
      );

    await requestProcessor.fetch(url, settings);
    return { transforms: [], primaryData: record };
  },
```

as i go through the code the JSON data is calling resourceIdentity but not serialize
thus the body remains unserialized on request

**Comment by dgeb** [comment]
> i have a custom serialiser configured for remote source but the serializer is not being called when sending this request.

Are you passing the `SerializerClass` option to your JSONAPISource when instantiating it?

https://github.com/orbitjs/orbit/blob/master/packages/%40orbit/jsonapi/src/jsonapi-source.ts#L58

If this is working, which methods are not being called?

Perhaps you could create a reproduction using an integration test in https://github.com/orbitjs/orbit/tree/master/packages/%40orbit/integration-tests/test

**Comment by tchak** [comment]
Are you expecting attributes/relationships to be sent with `addToRelatedRecords` request? If it's the case it's not going to work. According to `json:api` only identity is sent when adding a record to a relationship.

**Comment by TheLooseCannon** [comment]
@tchak yeah....im not trying to send attributes/relationships with addToRelatedRecords...but the thing is that....the format we use internally demands it to be serialized....even if it's just the ids. 

so i did a work around by extending `resourceIdentity`.
now i serialize the data on entering resourceIdentity but that has opened some new can of worms.

Adding/deleting a single resource from the related-records is working fine. Adding multiple records is also working fine

The problem right now is that when deleting multiple records
it works correctly only if not all records are deleted. i.e., only if out of N records N - x items are deleted. 
if all N related records are deleted, then they still persist in the local store ( even though it has been removed from the server)

my assumption is that when i delete all the related records ... server responds with a null array. but it looks as if the related records from the internal store have not been removed and receiving a null from the server is being interpreted as a value 'not send by the server' rather than 'not in the server'

i tried verifying this by doing the following
lets assume total related record count is N
so to delete all records i run
1. delete N - 1 Records
2. delete Nth Record

this seems to solve the issue
i hope my explanation was clear

so i was wondering how to solve this neatly...without such a work around

**Comment by dgeb** [comment]
@TheLooseCannon are you finding that your workaround is still necessary? If so, would you mind opening an issue on the main orbit repo, which is where `@orbit/jsonapi` lives, and ideally include a reproduction or failing test.
