### ISSUE TITLE
include is not working with addRecords

### ISSUE THREAD

**Issue by TheLooseCannon** [orbitjs/ember-orbit#261]
```js
response = await this.store.addRecord(
       {
		type: 'planet',
		...obj,
	},
	{
		sources: {
			remote: {
				include: 'moon',
			},
		},
	}
);
```

returns the included data allright from the server but after serialiser the included data dissappears...
how to get return of included data in orbit?

**Comment by dgeb** [comment]
With an event-logging strategy configured (`ember g data-strategy event-logging`) you should see `transform` events emitted from the remote source that represent adding/updating the included records. Are you seeing those events logged?

**Comment by dgeb** [comment]
If you're able to reproduce this problem, please open a PR with a failing test in the [@orbit/integration-tests](https://github.com/orbitjs/orbit/tree/master/packages/%40orbit/integration-tests) package.
