### ISSUE TITLE
Multiple Requests required when using remote id

### ISSUE THREAD

**Issue by TheLooseCannon** [orbitjs/ember-orbit#281]
i currently use my remote id to in all my routing

i.e., `localhost:4200/users/1234567`

where 1234567 is an actual id of a real user in the database
but when i reload a route, i can get the id from the route.

but this cannot be used to fetch the records as the key hasn't been mapped.
to fix this right now i have to call all users filtered by key

ex:- `localhost:4200/users?filter[key]=1234567
so as to get the mapping for 1234567
 
and then i send another request to fetch the data
```js
reponse = this.memory.query(q => q.findRecords('user')).filter({attribute: 'key', value: '1234567'})

userDetails = this.memory.query(q => q.findRecord({type: 'user', id: response[0].id})
```

here i'm sending 2 apis instead of one. how to fix this

**Comment by tchak** [comment]
Yes, the current handling of id/lid/remoteId/keys is not great and very confusing. We are planning on tackling it in Orbit 0.18

**Comment by TheLooseCannon** [comment]
@tchak as i have been going through the code, i noticed that the issue with remoteId and keys is that on initial loading, i.e.,
suppose we are loading the url `/profile/1234567890/details` directly and have to fetch the resource profile with id: 1234567890
orbit fails to identify the id '1234567890' as no keymapping has been done so far. 

so in such a case the work around that i have implemented is to call a api request without the id(like shown in [comment](https://github.com/orbitjs/ember-orbit/issues/281#issue-651775691)) so as to initiate a key mapping first and then using this mapping to send my desired request. 

if we were to add a check where if the keymap is not present, the Id is sent as provided or something similar to that, wouldn't we be able to solve this problem? 
just asking. would love to contribute

**Comment by dgeb** [comment]
In v0.17 beta, everywhere that you can specify a record identity `{ type, id }`, you can alternatively specify `{ type, key, value }`. 

These should now work:

```typescript
let  user = await this.memory.query((q) => q.findRecord({ type: 'user', key: 'remoteId', value: '1234567' });

// or simpler
let  user = await this.memory.findRecord({ type: 'user', key: 'remoteId', value: '1234567' });
```

Only a single request will be made. If the key doesn't exist in your `keyMap`, a fresh `id` will be generated and the mapping will be added.
