### ISSUE TITLE
[RFC] Namespace methods on Model class

### ISSUE THREAD

**Issue by tchak** [orbitjs/ember-orbit#283]
I quite like the pattern in certain ORMs where all the model methods are namespaced one way or another. I can think of several strategies.

One is the strategy used in https://vincit.github.io/objection.js/ . It consists in prefixing all the instance members on the model by a `$`. We could obviously decide on some other symbol.

```ts
planet.$remove();
planet.$relatedRecord('moons');
```

Another option would be to have a namespace on the model. I don't necessarily have a good suggestion for the namespace name.

```ts
planet.$.remove();
planet.$.relatedRecord('moons');

planet.api.remove();
planet.api.relatedRecord('moons');
```

Another option would consist in namespacing attributes and relationships.

```ts
planet.remove();
planet.attributes.name;
```

I don't think this is very ergonomic. It has the appeal of bringing the best guarantee of no conflicts but I think there other ways to deal with conflicts (serializer).

To me the main value of this proposition is to make it clear what belongs to the framework and what belongs to developer.

My preferred option is the first one.

**Comment by dgeb** [comment]
> My preferred option is the first one.

I agree. Let's deprecate the built-in `Model` methods and props in ember-orbit.

I'm also going to follow this pattern in Orbit query/transform builders and terms.
