### ISSUE TITLE
Model inheritance

### ISSUE THREAD

**Issue by chbonser** [orbitjs/ember-orbit#304]
Given the following models, I would expect `Planet` to inherit `name`, `moon`, and `sun` but it does not. Moving those declarations to `Planet` works but I lose the value of shared code. Is this a bug or does ember-orbit recommend solving this in a different manner?

```js
import { Model, attr, hasOne, hasMany, key } from 'ember-orbit';

export default class Planet extends Model {
  @attr('string') name;
  @hasMany('moon', { inverse: 'planet' }) moons;
  @hasOne('star') sun;
}
```

```js
import Planet from './planet.js'

export default class Earth extends Planet {
}
```

**orbit version:** ember-orbit@0.17.0-beta.5

**Comment by tchak** [comment]
I have an idea of what's going on. We use `reflect-metadata` on the model prototype to store schema information. I am pretty sure it creates issues with inheritance.

**Comment by chbonser** [comment]
Thanks @tchak. Let me know if there is a way I can help.

**Comment by chbonser** [comment]
@tchak Thanks for the updates to ember-orbit today. I pulled down master to check this out and somethings are better... some are worse. I'm trying to create a test case for what I'm seeing but struggling to do so. Perhaps you could provide some guidance.

I have a set of model classes that look roughly as follows...

```js
class NamedModel extends Model {
  @attr('string') name;
}

class Moon extends NamedModel {
  @hasOne('planet', { inverse: 'moons'}) planet;
}

class Ocean extends NamedModel {
  @hasOne('planet', { inverse: 'oceans'}) planet;
}

class Continent extends NamedModel {
  @hasOne('planet', { inverse: 'continents' } planet;
}

class Planet extends Model {
  @hasMany('moons', { inverse: 'planet' }) moons;
  @hasMany('oceans', { inverse: 'planet' }) oceans;
  @hasMany('continents', { inverse: 'planet' }) continents;
}
```

The issue is that orbit is throwing an `IncorrectRelatedRecordType` error with a message that is roughly `Schema error: Relationship definition oceans for model definition planet does not accept record of type moons`.

I can cause the error in two ways in my app:
1. When I load a planet via a jsonapi source with relationship identifiers for one of the `hasMany` relationships.
2. When I create a fork, then add an `ocean` (or moon or continent) record with the planet relationship.

I have a branch of `ember-orbit` where I've tried adjusting the test models to roughly match my setup but I can't make it fail. Any ideas?

One other observation: If I comment out the `hasOne planet` relationships on the models I'm not using at the moment, then things work. It appears that the inheritance is messing with how relationships get defined.

**Comment by tchak** [comment]
I know what is happening. Will fix soon.

**Comment by tchak** [comment]
https://github.com/orbitjs/ember-orbit/pull/310

**Comment by dgeb** [comment]
#310 has been merged and looks solid. Thanks @tchak!

I'm pretty sure this has been resolved now, and we'll get another beta release out ASAP. Of course, please let us know if you continue to have problems @chbonser
