### ISSUE TITLE
Some acceptance tests fail after a test is complete after upgrading to 0.17 beta

### ISSUE THREAD

**Issue by chbonser** [orbitjs/ember-orbit#307]
A large number of my acceptance tests fail for the following error after upgrading to 0.17 beta. These errors only occur after the test is complete (during tear down). 

```
Uncaught (in promise) Error: Attempted to associate a destroyable child with an object that is already destroying or destroyed at Object.associateDestroyableChild [as _associateDestroyableChild]
```

**Comment by tchak** [comment]
Interesting. In 0.17 I added a much more extensive cleanup on cache/identityMap. It is possible that it is too aggressive. Would be great if there was a way to have a simpler reproduction case.

**Comment by chbonser** [comment]
I don't have a simple reproduction case yet. I'll keep trying but I thought I'd post it before I did just in case someone else stumbles into this in the mean time.

**Comment by chbonser** [comment]
Here are two new clues that I can't quite make sense of... 

### First
To create the error I need to have the controller and template outlined below AND open a modal, fork the store, add a new 'moon', and finally merge the store.

### Second
This is the mysterious clue... I replaced a computed property in an ember controller with equivalent logic using helpers from [ember-composable-helpers](https://github.com/DockYard/ember-composable-helpers#table-of-contents) and the error went away.

So I replaced something like this...
```js
export default class SomeController extends Controller {
  @computed('this.model.planet.moons.@each.updatedAt')
  get updatedAt() {
    return this.model.planet.moons.mapBy('updatedAt').join(',');
  }
}
```

With...
```hbs
  {{join ',' (map-by 'updatedAt' this.model.planet.moons)}
```

And boom, error is gone.

**Comment by tchak** [comment]
* Do you in your code call `forkedStore.destroy()` after merge?
* Can you try to get from the trace with call to `associateDestroyableChild`? We call it in a couple of places: to associate forked store to its parent store and to associate a model to its cache.

**Comment by chbonser** [comment]
I don't call `destroy()` on any of my forks. I've added it but it does not change the error.

Stack trace:
<img width="1115" alt="Screen Shot 2020-09-24 at 2 34 39 PM" src="https://user-images.githubusercontent.com/1022582/94191493-314c4e80-fe73-11ea-834b-d4dfcec799d4.png">

**Comment by tchak** [comment]
Do you have any errors like this outside of tests? What happens here is that at the time the model instance is created the store is already destroyed. This looks like it could be an issue with store instance leaking between test teardown.

**Comment by chbonser** [comment]
This only occurs in tests.

**Comment by dgeb** [comment]
@chbonser I recall you mentioning that your test suite is green on the latest beta. Is this ok to close now?

**Comment by chbonser** [comment]
Yes, I think we can close this. I had a few places where it was possible to bleed associations between forks. The timing of tests made it more evident.
