### ISSUE TITLE
store.query resolves before last response is populated in the store (0.17 beta)

### ISSUE THREAD

**Issue by chbonser** [orbitjs/ember-orbit#312]
Consider the following query:
```js
let remoteQueryOptions1 = {
  settings: {
    params: {
      "filter[id]": ids1,
    },
  },
};

let remoteQueryOptions2 = {
  settings: {
    params: {
      "filter[id]": ids2,
    },
  },
};

store.query((q) => [
  q.findRecord('foo').options({ sources: { remote: remoteQueryOptions1 } }),
  q.findRecord('foo').options({ sources: { remote: remoteQueryOptions2 } }),
]);
```

I see 2 network requests succeed in the network tab, _but the promise resolves before the data in the second request is populated in the store_. If I wait some time (1 sec) then the data is present.

**Comment by chbonser** [comment]
Delaying by use of [next](https://api.emberjs.com/ember/3.21/functions/@ember%2Frunloop/next) is enough for the data to populate.

**Comment by dgeb** [comment]
Hmmm ... that's surprising 🤔 Do you have only blocking query + sync strategies in place?

I'm currently reworking the code around multiple-query execution to allow multiple-expression query requests to be made in parallel or in series, so I should have a new version to test soon. This code is entirely on the orbit side (vs. ember-orbit) so I'll confirm that tests are in place there.

**Comment by chbonser** [comment]
My `remote-request` and `remote-update` are blocking. `remote-sync` is non-blocking.

**Comment by dgeb** [comment]
You will need your sync strategy to be blocking as well to guarantee that the full request+sync cycle completes prior to the resolution of a request.

**Comment by chbonser** [comment]
Hah. That makes sense. Thanks.
