### ISSUE TITLE
findRecord promise does not resolve/reject for a 404 response

### ISSUE THREAD

**Issue by chbonser** [orbitjs/ember-orbit#313]
I have a blocking remote source with an error handler which essential mimics what is outlined here (https://github.com/orbitjs/todomvc-ember-orbit#pessimistic-error-handling).

When the server responds with a 404, I log the error in my error handler, then re-throw the exception BUT the promise returned by `store.findRecord` never resolves.

I was expecting the promise to reject so I can deal with it in my app code.

### Versions
```
    "@orbit/jsonapi": "^0.17.0-beta.8",
    "@orbit/local-storage": "^0.17.0-beta.8",
    "@orbit/local-storage-bucket": "^0.17.0-beta.8",
    "@orbit/serializers": "^0.17.0-beta.8",
    "@orbit/store": "^0.17.0-beta.2",
    "ember-orbit": 0.17.0-beta.5,
```

**Comment by dgeb** [comment]
@chbonser The latest orbit beta, v0.17.0-beta.11, no longer raises errors by default on 404s (although you can opt-in to the old behavior). This is described in the [release notes for beta.9](https://github.com/orbitjs/orbit/releases/tag/v0.17.0-beta.9).

Please give the latest betas a try, including ember-orbit v0.17.0-beta.6, and let me know if you continue to have issues.

P.S. The latest betas finally allow parallel fetch requests for multi-expression queries, which I know you've been interest in :)
