### ISSUE TITLE
Dependencies not defined in ember-orbit, like @orbit/local-storage-bucket not propagated through addons

### ISSUE THREAD

**Issue by RuslanZavacky** [orbitjs/ember-orbit#316]
Trying to follow examples in [peeps](https://github.com/cerebris/peeps-ember-orbit) repo, which are great. 

I am trying to apply it in the multi-addon setup, like:

```
my-app
 |- data-admin
   |- data-common
```

data-common has dependencies defined in `dependencies`:

```
"dependencies": {
  "ember-cli-babel": "^7.22.1",
  "ember-cli-htmlbars": "^5.3.1",
  "ember-concurrency": "1.3.0",
  "ember-concurrency-decorators": "2.0.2",
  "ember-orbit": "^0.16.9",
  "@orbit/jsonapi": "^0.16.7",
  "@orbit/indexeddb": "^0.16.7",
  "@orbit/indexeddb-bucket": "^0.16.3",
  "@orbit/local-storage": "^0.16.7",
  "@orbit/local-storage-bucket": "^0.16.3",
  "ember-auto-import": "^1.6.0"
},
```

When running `ember s` inside `data-common` - everything is fine, all deps work and are injectable. 

When running in `data-admin` and `app`, only deps defined inside ember-orbit propagates, but not the additional ones. This is what I see in `window.requirejs.entries`:

```
@orbit/coordinator, @orbit/core, @orbit/data, @orbit/identity-map, @orbit/memory, @orbit/utils
```

So we are missing `@orbit/jsonapi`, `@orbit/indexeddb` etc. the ones that are defined otside of `ember-orbit` 

I do see [this config](https://github.com/cerebris/peeps-ember-orbit/blob/master/ember-cli-build.js#L24) in the peeps app. I've tried to replicate that inside `data-common` addon as follows in `index.js`:

```
  included() {
    let app = this._findHost();
    const addonConfig = app.project.config(app.env)['orbit'] || {};

    addonConfig.packages = [
      '@orbit/jsonapi',
      '@orbit/indexeddb',
      '@orbit/local-storage',
      '@orbit/indexeddb-bucket',
      '@orbit/local-storage-bucket'
    ];

    this._super.included.apply(this, arguments);
  },
```

But that didn't help.

Any ideas what I am missing? 

Thank you!

**Comment by dgeb** [comment]
@RuslanZavacky I'm so sorry for the delay in responding to your issue. I haven't updated peeps-ember-orbit in a while, but I can do that soon. If you're interested, in the mean time, I'd recommend checking out https://github.com/orbitjs/todomvc-ember-orbit and the README there for examples.

The config from peeps-ember-orbit is thankfully no longer needed with the latest ember-orbit releases (v0.16.9 and v0.17.0-beta.6). Using `ember-auto-import` eliminates the need to manage the orbit-specific packages - imports should now "Just Work". Please let me know if you try things out again and have any issues and I'll try to be much more responsive. Sorry again about the late response.
