### ISSUE TITLE
Adding a validation function to the data models in orbit

### ISSUE THREAD

**Issue by TheLooseCannon** [orbitjs/ember-orbit#322]
I was considering adding a validation function to the data model class, but has been unsuccessful in doing so until now. 
during this i noticed that the data-model is not being initiated much. 

as far as i understood, orbit is only accessing its models to update schema in the store configuration. after this i couldn't find orbit initialising any data models. is my understanding correct? 

i tried adding a validating function to the data model but noticed that orbit is only creating an instance on app start and after that model initialisations are not done.

**Comment by TheLooseCannon** [comment]
could you suggest a way to implement a validation for the models?

**Comment by dgeb** [comment]
As we [discussed on gitter](https://gitter.im/orbitjs/orbit.js), these are my general recommendations:

> I tend to handle validations at the form level, rather than in models. Sometimes different models have different validations depending upon their context. And multiple models often need to be edited together in a single form, which I almost always handle in a forked store.

With that said, I think there's a lot to be said for shareable validation conventions. I have some code which I use privately but have never extracted into open source, but I'd like to do that in the future.
