### ISSUE TITLE
Request: Support for local (non syncable) fields

### ISSUE THREAD

**Issue by JannikStreek** [orbitjs/ember-orbit#34]
In my current setup (main store: local storage, secondary: json, transformation: json => main) I need some fields in the schema which should be only available inside the main store, but not in the secondary store. Within a normal setup, every call to the api would overwrite these fields in the main store to `null` because these fields do not exist in the json.

My current (hacky) solution overwrites the ```deserializeRecord``` method to get this behaviour:

```
App.Serializer = OC.JSONAPISerializer.extend({
  deserializeRecord: function(type, id, data) {
    if (id) {
      data[this.schema.models[type].primaryKey.name] = id;
    }
    if(type === 'item') {
      var oldItem = OrbitLocalSource.retrieve(type, data.id); //main store
      if (oldItem !== undefined) {
        data.nonSyncableField = oldItem.get('nonSyncableField');
      }
  }
  var normalized = this.schema.normalize(type, data);
  return normalized;
});
```

Instead, cool would be to have something like this:
```
App.Item = EO.Model.extend({
  title: EO.attr('string', {transformable: false})
})
```

What do you think?

P.S.: I am working on a fairly complex project and orbit just works, thanks :thumbsup:

**Comment by dgeb** [comment]
We probably want to support some level of source-specific configurations per-model-field. However, a generic `transformable` attribute that's not source-specific won't work. Let's think about how to make this source-specific.
