### ISSUE TITLE
Integrating with newer test waiters system

### ISSUE THREAD

**Issue by ef4** [orbitjs/ember-orbit#340]
I would like to register a source with ember's test waiter system so that this source is included in the default Ember `settled` state. This seems to work:

```js
import SourceClass from '@orbit/jsonapi';
import { registerWaiter } from '@ember/test';

let currentSource;
registerWaiter(function () {
  return (
    currentSource.requestQueue.empty &&
    !currentSource.requestQueue.processing &&
    currentSource.syncQueue.empty &&
    !currentSource.syncQueue.processing
  );
});

export default {
  create(injections = {}) {
    return (currentSource = new SourceClass(injections));
  },
};
```

However, current versions of the ember eslint plugin will complain about this use of `registerWaiter` and push you toward the [newer @ember/test-waiters system](https://github.com/emberjs/ember-test-waiters). That API no longer supports polling like this, and instead wants to wrap each asynchronous operation.

Since I would guess most sources don't want to build this in by default, would it be appropriate to emit events from the sources that one could observe in order to notice each time a task is enqueue or resolved? Is there an existing hook?

I'm aware of `waitForSource`, but that serves a different purpose than what I'm trying to do here. Especially for people porting from ember-data, it's very helpful to make a remote source always block `settled`.

**Comment by dgeb** [comment]
@ef4 Each of these queues is an Orbit `TaskQueue`. When the queues are empty they emit a [`complete` event](https://github.com/orbitjs/orbit/blob/main/packages/%40orbit/core/src/task-queue.ts#L344), which you can listen for:

```ts
currentSource.requestQueue.on('complete', () => { 
  // optionally return a promise here if you want to delay future actions of the queue until the promise resolves or errors
});
```

Remember to cleanup with `off`.

**Comment by ef4** [comment]
Thanks. Is there a corresponding event for going from empty to active?

**Comment by dgeb** [comment]
[`beforeTask`](https://github.com/orbitjs/orbit/blob/main/packages/%40orbit/core/src/task-queue.ts#L370) is emitted before each task in the queue is processed. I think this is most like an "active" indicator.

Another event to be aware of is [`change`](https://github.com/orbitjs/orbit/blob/main/packages/%40orbit/core/src/task-queue.ts#L415) which is emitted whenever the contents of the queue change, but this may happen when the queue is complete or processing has paused and its contents are changed.

**Comment by ef4** [comment]
Thanks, that set me on the right track. I ended up going with `beforeTask` for start and `task` or `fail` for end. Here is a utility that may help others (and could potentially go into ember-orbit):

```js
import { buildWaiter } from '@ember/test-waiters';

export function buildOrbitWaiter(label) {
  let waiter = buildWaiter(label);

  const taskTokens = new WeakMap();

  function taskStarted(task) {
    let token = waiter.beginAsync();
    taskTokens.set(task, token);
  }
  function taskEnded(task) {
    let token = taskTokens.get(task);
    if (token) {
      waiter.endAsync(token);
    }
  }

  function waitForSource(source) {
    source.requestQueue.on('beforeTask', taskStarted);
    source.requestQueue.on('task', taskEnded);
    source.requestQueue.on('fail', taskEnded);
    source.syncQueue.on('beforeTask', taskStarted);
    source.syncQueue.on('task', taskEnded);
    source.syncQueue.on('fail', taskEnded);
    return source;
  }

  return { waitForSource };
}
```

You use it like:

```js
import JSONAPISource from '@orbit/jsonapi';
import { buildOrbitWaiter } from '../lib/orbit-waiter';

let { waitForSource } = buildOrbitWaiter('data-source:rails');

export default {
  create(injections = {}) {
    return waitForSource(new JSONAPISource(injections));
  }
}

```

**Comment by dgeb** [comment]
Looks good @ef4 - thanks for sharing! I've opened tracking issue #341 to ensure that we add your work, or something similar, to ember-orbit soon.

**Comment by RobbieTheWagner** [comment]
Any updates on this?
