### ISSUE TITLE
Throws unintended exception while trying to assert about hasMany with no arg

### ISSUE THREAD

**Issue by ef4** [orbitjs/ember-orbit#343]
While upgrading from 0.16 to the 0.17.beta, I had code that calls `hasMany` with no arguments, which now tries to assert:

https://github.com/orbitjs/ember-orbit/blob/ee1a0c91206fe1fd1a866f6db63c0e3a27957c59/addon/-private/fields/has-many.ts#L39

But instead this throws:

> TypeError: Cannot read property 'type' of undefined

because `relDef` is undefined.

**Comment by dgeb** [comment]
Ah good catch. This should be resolved with a simple `?`:

```diff
- assert('@hasMany() requires a `type` argument.', relDef.type !== undefined); 
+ assert('@hasMany() requires a `type` argument.', relDef?.type !== undefined); 
```
