### ISSUE TITLE
No 'attributes' saved to indexeddb

### ISSUE THREAD

**Issue by mrloop** [orbitjs/ember-orbit#396]
I've created a minimal app to demonstrate issue, please see the last commit which adds the app code https://github.com/mrloop/orbit-indexeddb-no-attr-issue/commit/ebf3385b0506f0acbfc1b64f9e55b43a3418137e. As described in the code comments when a record is saved to the indexeddb backup store and it has no attr fields , either the Model doesn't declare any using the @attr decorator or they are set to `undefined` then when saved to indexeddb the record has no `attributes`, the key isn't present. 

If the app is reloaded, and the records loaded from the indexeddb backup the data isn't displayed as expected. In the example the timeTrial model is saved to indexeddb without any attributes, when the app is reloaded when trying to display a record related to the timeTrial, the course record it's name isn't displayed.

![orbit-attributes](https://user-images.githubusercontent.com/12345/156879056-3f8f768f-5cbe-45c5-953c-f366fbdaf2e6.gif)

**Comment by dgeb** [comment]
@mrloop thanks so much for reporting this! Thanks to your reproduction, I was able to track down and fix the error in #397.

Your reproduction should now work by upgrading to ember-orbit 0.17.1.
