### ISSUE TITLE
Automatically lookup ('find') linked async records as they are requested

### ISSUE THREAD

**Issue by leejt489** [orbitjs/ember-orbit#41]
Something like how ember-data does it: https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/relationships/relationship.js#L329-L337 and https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/relationships/relationship.js#L236-L244

Pretty important for smoothly nesting templates and controllers in my opinion and also for transitioning from ember-data.

**Comment by pixelhandler** [comment]
@leejt489 @dgeb any updates on the best way to access the relationship. 

I tried using the route's afterModel hook for a post that I know has comments but for some reason the comments are empty, see: https://github.com/pixelhandler/blog/blob/comments/app/routes/post/detail.js#L9-L11

**Comment by dgeb** [comment]
Oh my, this issue has been open a while. Sorry for not fully addressing all the questions sooner! 😅 

---

The members of relationships can now be directly accessed on orbit models:

```javascript
let author = post.author; // returns an `Author` model
let comments = post.comments; // returns an array of `Comment` models
```

Relationships, and all other fields, will stay updated as values in the underlying cache are updated.

If you want to force an update of the cache, you can re-query the associated `Store`:

```
await store.query((q) => q.findRelatedRecord(post, 'author');
await store.query((q) => q.findRelatedRecords(post, 'comments');
```

You can also pass query options, such as pagination and include params, [as described in the orbit docs](https://orbitjs.com/docs/next/querying-data#query-options).
