### ISSUE TITLE
Model lifecycle events

### ISSUE THREAD

**Issue by opsb** [orbitjs/ember-orbit#46]
I'm considering the equivalent of rails model callbacks in ember-orbit(after_create, before_save etc.). It looks like this could be implemented using orbit.js' [notifications and events](https://github.com/orbitjs/orbit.js#notifications-and-events). @dgeb have you considered whether this is a desirable feature to have and does that seem like the most natural place to integrate them?

**Comment by dgeb** [comment]
Each model now has access to its corresponding store.

Also, relationships can be modified directly from a model. For example:

```
      this.transaction.addRecord({type: 'notification'})
        .then((notification) => {
          this.get('model.notifications').pushObject(notification);
        });
```
