### ISSUE TITLE
'FindLinked' not setting properties with JSON API source

### ISSUE THREAD

**Issue by leejt489** [orbitjs/ember-orbit#47]
I am having an issue where records that I'm requesting are coming back with null properties, though the server is returning values for those properties.  I'm a little confused as to what's going in, but here is my digging (bear with me):

To cut to the chase, I think the problem has something to do with this line here https://github.com/orbitjs/ember-orbit/blob/master/lib/ember-orbit/store.js#L196

I am using the orbit common JSON API source.

First, I call `reload` on a hasMany field to fetch the data for each of the related items.  This calls `findLinked` which fires off a request to the JSON API source.  The request then calls the orbit common _findLinked method which calls the JSON API source's _find method.  This calls _findMany, which fires off an ajax request.

Now at this point, orbit's `settleTransforms` gets called before the ajax request returns a response, which fires off some `didTransform` events for the returned records, eventually resulting in a call to `RecordArrayManager.recordDidChange`.  Seems all good.

OK so now we're back in the `.then` callback from the ajax request (which is inside the JSON API source's _findMany), which deserializes the records and makes another call to `settleTransforms` and orbit does some more transformation stuff in the background, and returns THE CORRECT array of records from the server.

Now for the good part.  Back in `findLinked` in the callback from orbit source https://github.com/orbitjs/ember-orbit/blob/master/lib/ember-orbit/store.js#L196, the variable `data` holds the CORRECT data as it should.  Then, in the call to `_lookupFromData` we get to here https://github.com/orbitjs/ember-orbit/blob/master/lib/ember-orbit/store.js#L336 `return _lookupRecords(type, id);` which takes us to here 'https://github.com/orbitjs/ember-orbit/blob/master/lib/ember-orbit/store.js#L306'.  At this point `record` does not have any of the info returned from the server.  On top of that `record.__ember_meta__.cache` has the record's properties but set to `null` (I think this may be because these records are loaded asynchronously, so the first time they were requested and cached, the values were null)!  This is the value that gets returned all the way back to my controller.

I'm not sure what the solution is.  Is it as simple as something like merging the `data` object into the values returned from `_lookupRecords` here https://github.com/orbitjs/ember-orbit/blob/master/lib/ember-orbit/store.js#L336?  What is confusing me is that orbit seems to rely heavily on the records' `__ember_meta__.cache` property, which I don't fully understand.

@dgeb Happy to provide more info.

**Comment by dgeb** [comment]
I'm closing this because the JSONAPISource has been rewritten and the `findLinked` method has been replaced with the more general `query` method. We'll publish updated docs for the new interfaces soon.
