### ISSUE TITLE
Polymorphism

### ISSUE THREAD

**Issue by juggy** [orbitjs/ember-orbit#49]
Orbit doesn't seem to have support for polymorphism. Am I right?

How are you handling it at the store level as well as at the relationship level?

Thanks.

**Comment by brancusi** [comment]
+1

**Comment by dgeb** [comment]
JSON API now supports polymorphism and so it will be supported fully by Orbit as well.

Related: https://github.com/orbitjs/orbit.js/issues/110

**Comment by dgeb** [comment]
Polymorphism has landed in JSONAPI and Orbit itself. Relationships can include multiple types of records now that identity data is tracked as `{ type, id }`.
