### ISSUE TITLE
Unhandled change for replace operation in RecordArrayManager

### ISSUE THREAD

**Issue by pixelhandler** [orbitjs/ember-orbit#50]
See RecordArrayManager#_processChange
https://github.com/orbitjs/ember-orbit/blob/master/lib/ember-orbit/record-array-manager.js#L66-L77

This line logs out an unhandled change...

```js
console.log('!!!! unhandled change', path.length, operation);
```

Like so: 

```text
 !!!! unhandled change 5 Object {op: "replace", path: Array[5], value: "488c793d-20cb-4f9d-aa2f-7b77b82f2e24"}
  op: "replace" 
  path: Array[5]
    0: "author"
    1: "5c9b62ec-1569-448b-912a-97e6d62f493e"
    2: "__rel"
    3: "posts"
    4: "488c793d-20cb-4f9d-aa2f-7b77b82f2e24"
  value: "488c793d-20cb-4f9d-aa2f-7b77b82f2e24"
```

A "replace" operation with path.length of 5 is not handled however the RecordArrayManager#_processChange does handle add and remove.

The use case I have is: 
Given a post with a linked author (and vice-versa) I called `author.removeLink('posts', post)` to remove the linked post from the author resource then called `post.remove()` to destroy the post resource.

I'll have to dig in to see why the replace operation was fired, it seems like the operation is odd, looks like it wants to replace the existing value for the author's linked post id.

**Comment by dgeb** [comment]
We've completely refactored operations with the merger of the `rethink` branch. Operations are now at a higher level that's more record-aware. The `replaceHasMany` operation should now handle your needs here.
