### ISSUE TITLE
Configuration for snake_cased irregular noun

### ISSUE THREAD

**Issue by johanobergman** [orbitjs/ember-orbit#53]
My api currently has an endpoint for `stamina_activities` (god, why did I pick this disastrous name), and I fail miserably every time I try to get this endpoint to play nicely with third-party libraries.

I have an ember-cli model at `stamina-activity.js`, which is used by the store as `store.find('staminaActivity')` and in a has many relationship like so: `model.get('staminaActivities')`, defined by `staminaActivities: EO.hasMany('staminaActivity')`.

How do I make Orbit understand this mess? I've added the following pluralization rules to the schema:

``` javascript
var EO_Schema = EO.Schema.extend({
  pluralize: function(word) {
    if (word === 'staminaActivity') return 'staminaActivities';
    return word + 's';
  },

  singularize: function(word) {
    if (word === 'staminaActivities') return 'staminaActivity';
    return word.substr(0, word.length - 1);
  }
});
```

and i'm using the snake -> camel defined in [peeps-ember-orbit](https://github.com/cerebris/peeps-ember-orbit/blob/master/app/initializers/ember-orbit.js#L98-L106).

It works alright when fetching records directly using `store.find('staminaActivity')`, but when they are sideloaded, I get the following error:

```
TypeError: Cannot read property 'keys' of undefined
    at Class.extend.initDefaults
    at Class.extend.normalize
    at Serializer.extend.deserializeRecord [as _super]
    at JSONAPISerializer.default.extend.deserializeRecord
```

The `model` parameter in the `normalize` method at this time is `stamina_activitie` (without the `s`) when it should be `staminaActivity`. I can get rid of the error by adding some fancy logic in Schema#singularize (`if (word === 'stamina_activities') return 'staminaActivity';`), but the records are still not loaded and `model.get('staminaActivities')` returns an empty array. Calling `reload()` on it does nothing, and sends no request.

**Comment by dgeb** [comment]
I'm very sorry that I didn't respond to this issue much earlier. If you are still interested in using orbit and ember-orbit, there is a new set of guides over at http://orbitjs.com. And if you have any trouble configuring a JSONAPISource or JSONAPISerializer to hit your endpoint, please let me know and I'd be glad to help you troubleshoot.
