### ISSUE TITLE
Replace hasMany relationship

### ISSUE THREAD

**Issue by opsb** [orbitjs/ember-orbit#55]
@dgeb I've got a rough sketch of the firebase source working now so I'm now looking at ordered arrays again. It doesn't look like ember-orbit supports replacing hasMany relationships yet. Do I take it this needs to be added to record-array-manager? I'm looking at adding a _linkWasReplaced to go with _linkWasAdded and _linkWasRemoved.

**Comment by dgeb** [comment]
Has-many relationships can now be replaced using the `replaceHasMany` operation.
