### ISSUE TITLE
Lazy loading relationships

### ISSUE THREAD

**Issue by opsb** [orbitjs/ember-orbit#57]
At the moment relationships only call store.retrieve to load records. But there's no guarantee that the record has actually been loaded into the store. I would expect store.findLinked to be called both when a relationship is first loaded and then when there are changes. What's the expected data flow here? 

I'm considering a couple of things:

1) Use calls to objectAtContent to lazily call store.findLinked - once the relationship has been loaded a flag would be set on the relationship, loaded = true.

2) Add an autoReload option e.g.

	export default EO.Model.extend({
		comments: EO.hasMany('comment', {inverse: 'user', autoReload: true}),
	});

which would instruct the relationship to call reload() (from link-proxy-mixin) whenever the array was changed. 

@dgeb I'll be getting on with this today so let me know if you think this is the wrong direction.

**Comment by opsb** [comment]
The main use case for this is traversing relationships in templates e.g.

    {{#each group in groups}}
        <ul>
        {{#each task in group.tasks}}
            <li>{{task.name}}</li>
        {{/each}}
        </ul>
    {{/each}}

Currently the above code will only call use source.retrieve, if findLinked has never been called on the relationship then the records won't be in the store. Somehow source.findLinked needs to be called at the appropriate time (possibly by hooking into objectAt in the relationship's arrayproxy).

**Comment by opsb** [comment]
@dgeb we've made some good progress on this today, hasOne's are now lazy loading. You can take a look at the branch over at https://github.com/lytbulb/ember-orbit/commits/lazy_loading. 

Something we haven't figured out is how to determine if records in a record_array_proxy have been loaded or not (as opposed to being just stubbed in the typeMap). Is there anything we could key off or do we need to add something to track this?

**Comment by dgeb** [comment]
Let's re-examine lazy-loading relationship issues in the context of the `rethink` changes.
