### ISSUE TITLE
How do transform-connector, transformations, actions and operations fit together

### ISSUE THREAD

**Issue by opsb** [orbitjs/ember-orbit#63]
I've got a pretty good mental model of how everything works in orbit.js and ember-orbit now. One area which is very hazy though is what's happening with the transformation pipeline, in particular how the transform-connector mediates the processing flow in transformable. @dgeb could you spare a few minutes in IRC at some point to answer a few questions? I'd be very happy to write it up in the wiki.

**Comment by opsb** [comment]
The reason I'm looking at this at the moment is because I've got a test which fails because the transformations hang. It's proving extremely difficult to debug...

**Comment by dgeb** [comment]
@opsb sure, just ping me in IRC and I'll respond as soon as I'm available.

**Comment by dgeb** [comment]
This issue should no longer be applicable with the `rethink` merger.
