### ISSUE TITLE
Creating an object graph

### ISSUE THREAD

**Issue by opsb** [orbitjs/ember-orbit#67]
It's currently possible to create an object graph using syntax like:

    store.create('user', {
      organisation: organisationAttributes
    });

but this isn't mentioned in the docs anywhere. Is this syntax going to be supported ongoing?

**Comment by opsb** [comment]
Ok, so it looks like this accidentally half works but isn't really supported. Coming from rails I think it would be great if we could support so I'm going to take a look and see if I can put a PR together.

**Comment by dgeb** [comment]
With the `rethink` merger, `store.addRecord` has replaced `store.create`.
