### ISSUE TITLE
Reduce number of PUT requests when setting properties

### ISSUE THREAD

**Issue by OiNutter** [orbitjs/ember-orbit#68]
Using Ember-Orbit with a JSONAPISource, as soon as I set a property on a model it sends a PUT request to update that property on the server. This isn't so bad and I can see that potentially being intended behaviour, although I would prefer it to work more like Ember-Data where changes aren't commited to the source until I call `save`, but what I would expect to happen is that if I call `setProperties` with a list of properties to update it would set a single PUT request updating all of them, however it appears it still sends one request per property. 

I'm not sure if there is some logic behind why it is done this way but it seems kind of inefficient to me and seeing as I'm building this as part of a mobile app, a little too bandwidth heavy for my tastes.

Couldn't see any obvious way of overriding this but if someone can point me in the right direction, or suggest a better way of dealing with this I'd be most grateful.

Cheers

**Comment by pixelhandler** [comment]
@OiNutter personally I like the way orbit works. For editing I often defer when the app makes property changes, for example I may not bind a model to form inputs and instead use an event to update the property on blur.

**Comment by leejt489** [comment]
@pixelhandler I agree with your way of doing things; it is generally best to let events handle property changes (data down actions up), but I think @OiNutter is saying that you can't update multiple properties with a single PUT request.  I haven't personally verified this behavior, but if it takes 5 requests to update 5 properties, even if triggered by only one action (say filling out a form and submitting), then that is a problem!

**Comment by opsb** [comment]
Another option is to use an editing context, there's an example in https://github.com/cerebris/peeps-ember-orbit/blob/master/app/initializers/ember-orbit.js#L8. To use it you do:

    var context = store.createContext();
    context.add('project').then(function(project){
        project.set("name"); // not propagated yet
    });
    context.commitTransaction(); // add project and project.set("name") propagated

We need to add this into ember-orbit properly.

**Comment by OiNutter** [comment]
Yeah I'm saying it takes multiple requests to update multiple properties even if triggered by one action. I've basically ended up doing what you've suggested and not binding directly to the properties but the multiple requests is not good. 




Would the editing context fix this?



—

**Comment by opsb** [comment]
Using the editing context would fix this yes, changes won't be "saved" until you call context.commitTransaction(). Bear in mind though that this is a sketched out idea at the moment. We're using it in our app and it works great. Hopefully we'll be able to firm up the API and get it into ember-orbit soon.

**Comment by OiNutter** [comment]
Ok, so the editing context works great but it's still sending a single PUT request per property changed when I call commitTransaction(). Any ideas?

**Comment by dgeb** [comment]
We've recently introduced a [coalesceOperations](https://github.com/orbitjs/orbit.js/blob/master/lib/orbit/lib/operations.js#L159-L185) function in orbit that will be used in coordination with editing contexts to minimize a set of operations.

**Comment by OiNutter** [comment]
Would that version of coalesceOperations be suitable to just straight replace the one used in https://github.com/cerebris/peeps-ember-orbit/blob/master/app/initializers/ember-orbit.js#L47?

**Comment by opsb** [comment]
@OiNutter yes it's a drop-in replacement. The main difference is that it will consolidate attribute/link operations onto record operations. For reference, the import is

    import { coalesceOperations } from 'orbit/lib/operations';

**Comment by OiNutter** [comment]
Bad news, even using the editing context and that coalesceOperations method it's still sending one PUT request per property. 
To clarify what's happening;
* I have a model with property A and property B
* I update both property A and property B
* I call commitTransaction on the context
* One PUT request is sent to update property A and a second is set to update property B.

I would expect a single PUT request updating both property A and B. If it helps I've tried this on the https://github.com/cerebris/peeps-ember-orbit example and the same thing happens.

**Comment by opsb** [comment]
If the record already exists then coalesce records won't help because it doesn't have the add record operation to consolidate the two changes into. I don't use the json adapter myself so someone else will have to jump in.

**Comment by dgeb** [comment]
I am rewriting the JSONAPISource for compatibility with the latest rev of JSON API. I'll test for this use case as part of the rewrite.

**Comment by dgeb** [comment]
Updates are now automatically coalesced to a minimal set when applied as part of a transaction.
