### ISSUE TITLE
retrieveLink trying to retrieve link for links field when saving record

### ISSUE THREAD

**Issue by OiNutter** [orbitjs/ember-orbit#71]
Getting a strange issue when trying to save a new record. The POST request is getting sent through fine but when ember-orbit tries to process the returned json it's throwing an error in didTransform. Upon further investigation it appears that it's trying to call `Store._retrieveLink` on the `links` field. To be honest this could just be that I'm returning something invalid in my POST response but if I take the links field out it ends up trying to delete the relationship.

I can't post an exact copy of my POST json because of data sensitivity but I the basic structure is like this:

    {
        "data":{
            "id":"some-uuid-string",
            "propertyA": "a",
            "propertyB": "b",
            "links": {
                "relationship1":"some-other-uuid-string",
                "relationship2": [
                     "uuid-1",
                     "uuid-2"
                 ]
            }
        }
        "linked": {
            "dataType1": [array of loaded data types],
            "dataType2": [array of loaded data types]
        }
    }

Any ideas or more helpful information I can give you?

**Comment by dgeb** [comment]
Sorry for the long delay in responding @OiNutter.

We've refactored operations to be at a higher level that's more record-aware with the merger of the `rethink` branch. I don't believe this issue is still applicable.
