### ISSUE TITLE
Proposal: Blocking/non-blocking store API

### ISSUE THREAD

**Issue by opsb** [orbitjs/ember-orbit#74]
My app runs with a non-blocking connector to firebase. This means that UI updates are fast and the changes are saved in the background. 

I've now got a single case where I need to block when adding a record i.e.

    store.add('attachment', {filename: "report.xls"}).then(function(attachment){
        return uploadService.upload(file, attachment.id, userId);
    });

The uploadService is calling through to a service running on a different host and uses the attachment.id and userId to authorize the upload. The problem is that because store is running with a non-blocking connector the attachment isn't actually necessarily stored in firebase when the upload service tries to authorize the upload.

What I'm thinking about is allowing the store to have two connectors, one for blocking, one for non-blocking. That way we could support an API like:

    // default - configured as blocking or non-blocking when store is created
    store.add('attachment', {filename: "report.xls"}).then(function(attachment){
        return uploadService.upload(file, attachment.id, userId);
    });

    // blocking
    store.blocking.add('attachment', {filename: "report.xls"}).then(function(attachment){
        return uploadService.upload(file, attachment.id, userId);
    });

    // non-blocking
    store.nonBlocking.add('attachment', {filename: "report.xls"}).then(function(attachment){
        return uploadService.upload(file, attachment.id, userId);
    });

I have a workaround in place but I think this is a scenario that will crop up again and should be solved properly. 

### Alternatives:

Another option would be to just use two separate stores, this seems wasteful(for memory) and would make the sychronisation between the sources more complicated but would be easier to setup in the short term.

**Comment by dgeb** [comment]
It seems that you could create two transform connectors - one blocking and one non-blocking - that make use of the [`filterFunction`](https://github.com/orbitjs/orbit.js/blob/master/lib/orbit/transform-connector.js#L137). Your non-blocking connector could ignore transforms handled by your blocking connector and vice versa.

Obviously, this would all be in pure orbit, and not ember-orbit. We still need to consider how much of this functionality is exposed in ember-orbit as well.

**Comment by opsb** [comment]
Hmm, I'm actually using a fairly [custom connector](https://github.com/lytbulb/orbit-firebase/blob/master/lib/orbit-firebase/firebase-connector.js) so I could probably just implement the blocking/non-blocking switching in there. 

My only problem is that I currently hit a deadlock if I have both connectors (mem source <=> firebase source) blocking. Need some time to get back to that...

**Comment by dgeb** [comment]
I think the new Coordinator class should answer these needs.

@opsb please reopen if you want to discuss blocking / non-blocking APIs at the Store itself.
