### ISSUE TITLE
Proposal: model meta/configuration

### ISSUE THREAD

**Issue by opsb** [orbitjs/ember-orbit#77]
Allow models to specify configuration for Sources e.g. I need to specify that the task model should be embedded inside the project model when stored in firebase.

```
// task.js
export default EO.Model.extend({
  configuration: {
    embeddedIn: 'project'
  },
  name: EO.attr('string'),
  project: EO.hasOne('project', {inverse: 'disciplines'}),
  tasks: EO.hasMany('task', {inverse: 'discipline'}),
  label: Ember.computed.alias("name")
});
```

Thoughts:

1) Should we namespace configuration? e.g.

```
  configuration: {
    firebase: {
        embeddedIn: 'project'
    }
  },
```

2) Should the configuration be made directly on the source rather than being kept in the model? (personal preference is to keep it on the model).

**Comment by dgeb** [comment]
Superceded by https://github.com/orbitjs/orbit/issues/448

Once we allow source-specific options in `@orbit/data`, we can use a mechanism like you've proposed here to configure them in ember-orbit.
