### ISSUE TITLE
Integration with ember-cli

### ISSUE THREAD

**Issue by tute** [orbitjs/ember-orbit#8]
For integrating into an ember-cli project that used data, I'm doing:
1. Remove `ember-data` altogether (I suspect it was the source of the `The initializer 'injectStore' has already been registered` error). In my case it was tied to the models, `DS.RESTAdapter`, package and bower.json, and a custom `app/transforms/array.js`.
2. Add to `bower.json` (got this snippet from https://github.com/opsb/ember-orbit-todos/blob/master/bower.json):
   
   ```
   "orbit.js": "~0.2",
   "ember-orbit-development": "https://lytbulb-vendor.s3.amazonaws.com/ember-orbit/347f1d3/ember-orbit.js",
   "ember-orbit-production": "https://lytbulb-vendor.s3.amazonaws.com/ember-orbit/347f1d3/ember-orbit.min.js"
   ```
   
   This is related with https://github.com/orbitjs/ember-orbit/issues/7, about having an npm package for ember-orbit (that could require orbit.js itself).
3. Add `app/initializers/orbit-store.js`, similar to https://github.com/orbitjs/ember-orbit#initialization. Now stuck in there, with errors like `ReferenceError: Orbit is not defined`.

Are there blog posts or guidelines on how to integrate it into an existing project? If not, we may start off of this issue!

Thanks for your work.

**Comment by csprocket777** [comment]
Did a JSONAPISource + MemoryStore example of the todos app ever get created? I'm lost on how to get this to work with a remote REST API server.
