### ISSUE TITLE
Deprecation warning with observer in Ember 1.13.5

### ISSUE THREAD

**Issue by HenryVonfire** [orbitjs/ember-orbit#81]
Just and exactly ONE deprecation warning in `ember-orbit.amd.js`, solved by switching from:  

`updateFilter: Ember.observer(function() {
      Ember.run.once(this, this._updateFilter);
    }, 'filterFunction')`

to:

`updateFilter: Ember.observer('filterFunction', function() {
      Ember.run.once(this, this._updateFilter);
    })`

**Comment by dgeb** [comment]
Thanks for looking into this. I'm almost done with a big orbit refactor which will require an update to ember-orbit as well. I'll resolve this in the forthcoming release.
