### ISSUE TITLE
Convert to ember-cli addon

### ISSUE THREAD

**Issue by opsb** [orbitjs/ember-orbit#86]
- [ ] `ember install ember-orbit` should add orbit as bower dependency
- [ ] should expose `store` as a service

TBD:
* how should orbit be configured? 
* which interfaces should be public? (i.e. in the app directory)

**Comment by opsb** [comment]
Dupe of https://github.com/orbitjs/ember-orbit/pull/9

**Comment by opsb** [comment]
See https://github.com/orbitjs/ember-orbit/pull/9

**Comment by dgeb** [comment]
ember-orbit has been converted to a proper add-on (thanks to @opsb). 🎉 

Orbit is now installed as an npm dependency.

An initializer now configures a default store service.

There's still work tbd to improve the ergonomics, but that will be addressed in separate issues.
