### ISSUE TITLE
Introduce query/liveQuery and queryRecords/liveQueryRecords

### ISSUE THREAD

**Issue by opsb** [orbitjs/ember-orbit#89]
As discussed with @dgeb the following should be introduced

### cache
- [ ] cache.query - returns values
- [ ] cache.queryRecord - returns an individual record from identity map
- [ ] cache.queryRecords - returns records from identity map 
- [ ] cache.liveQuery - implemented but currently returns records from identity map, should return JSON Patches to add/remove/replaceAll values
- [ ] cache.liveQueryRecord - returns JSON Patches to replace record
- [ ] cache.liveQueryRecords - returns JSON Patches to add/remove/replaceAll records

### store
- [ ] store.query - returns values
- [ ] store.queryRecord - returns an individual record from identity map
- [ ] store.queryRecords - returns records from identity map
- [ ] store.liveQuery - returns JSON Patches to add/remove/replaceAll values
- [ ] cache.liveQueryRecord - returns JSON Patches to replace record
- [ ] store.liveQueryRecords - returns JSON Patches to add/remove/replaceAll records

**Comment by dgeb** [comment]
Now that the `rethink` branch has merged, and `query` and `liveQuery` methods are all record-aware, we should re-examine potential new interfaces on a one-by-one basis.
