### ISSUE TITLE
Allow orbit.js ES6 modules to be imported directly

### ISSUE THREAD

**Issue by opsb** [orbitjs/ember-orbit#90]
Currently orbit.js is included as a bower dependency that includes transpiled code. As the transpiled code isn't kept in the main orbit.js repo this is inconvenient as it requires orbit.js to be published to https://github.com/orbitjs/orbit-builds before it can be used in ember-orbit. 

In theory it should be possible to add orbit.js' ES6 modules directly into the broccoli pipeline which would allow orbit.js to be imported directly from https://github.com/orbitjs/orbit.js.

https://github.com/emberjs/data/blob/master/index.js has some clues but doesn't go as far as adding a source tree from an npm or bower dependency.

**Comment by dgeb** [comment]
Orbit is now imported as an npm dependency and the raw modules are added to the broccoli pipeline. Again, thanks @opsb 🎉
